#!/usr/bin/with-contenv bash

FLAGS=""

# configure `tailscale up`
if ! [ -v TAILSCALE_AUTHKEY ]; then
    echo '[!] TAILSCALE_AUTHKEY is not defined, this will print a login URL to the screen'
else
    FLAGS="${FLAGS} --authkey=${TAILSCALE_AUTHKEY}"
fi

if [ -v TAILSCALE_ADVERTISE_TAGS ]; then
    FLAGS="${FLAGS} --advertise-tags=${TAILSCALE_ADVERTISE_TAGS}"
fi

if [ -v TAILSCALE_HOSTNAME ]; then
    FLAGS="${FLAGS} --hostname=${TAILSCALE_HOSTNAME}"
fi

if [ -v TAILSCALE_USE_SSH ]; then
    FLAGS="${FLAGS} --ssh=${TAILSCALE_USE_SSH}"
fi

if [ -v TAILSCALE_ACCEPT_ROUTES ]; then
    FLAGS="${FLAGS} --accept-routes=${TAILSCALE_ACCEPT_ROUTES}"
fi

if [ -v TAILSCALE_BE_EXIT_NODE ]; then
    echo '[!] acting as an exit node, you may need to approve this in the admin console'
    FLAGS="${FLAGS} --advertise-exit-node=${TS_BE_EXIT_NODE}"
fi

echo "[cmd] tailscale up $FLAGS"
tailscale up $FLAGS

# configure serve or funnel

# endpoint exposed to network/public
ENDPOINT="--${TAILSCALE_SERVE_MODE} ${TAILSCALE_SERVE_PORT}"
# target it connects to
TARGET="${TAILSCALE_TARGET_MODE:=https}://localhost:${TAILSCALE_TARGET_PORT:=443}"

if [ -v TAILSCALE_SERVE_PORT ] && [ -v TAILSCALE_SERVE_MODE ]; then

    if [ -v TAILSCALE_FUNNEL ]; then
        echo "[cmd] tailscale funnel --bg ${ENDPOINT} ${TARGET}"
        tailscale funnel --bg ${ENDPOINT} ${TARGET}
    else
        echo "[cmd] tailscale serve --bg ${ENDPOINT} ${TARGET}"
        tailscale serve --bg ${ENDPOINT} ${TARGET}
    fi
    
fi

